apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
  labels:
    owner: tsisar
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pavlo.tsisar@desynclabs.com
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-private-key
    solvers:
    - http01:
        ingress:
          class: nginx