---
galaxy_info:
  author: k3s-cluster
  description: Gateway API CRDs installation role
  company: k3s-cluster
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 24.04
  galaxy_tags:
    - kubernetes
    - gateway-api
    - crd

dependencies: []
