controller:
  kind: Deployment
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  ingressClassResource:
    enabled: true
    default: true
  gatewayAPI:
    enabled: true
    gatewayClassName: nginx
    installCRDs: true