{
 "title": "PVC Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(pvc_usage_total, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Used - All",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pvc_usage_used_percent{}", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Used/Free - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pvc_usage_used{hostname=~\"$hostname\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pvc_usage_free{hostname=~\"$hostname\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Total - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pvc_usage_total{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "Free - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pvc_usage_free{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} - {{pvc}}"
    }
   ]
  },
  {
   "title": "Used - $hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pvc_usage_used{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} - {{pvc}}"
    }
   ]
  }
 ]
}