---
- name: Copy cluster secrets and certificates
  hosts: master
  become: true
  gather_facts: false

  vars:
    local_secrets_dir: "{{ lookup('env','HOME') }}/.kube/secrets"
    cluster_name: "{{ inventory_hostname }}"

  tasks:
    - name: Ensure local secrets directory exists
      file:
        path: "{{ local_secrets_dir }}"
        state: directory
        mode: '0700'
      delegate_to: localhost
      become: false

    - name: Fetch K3s server certificate
      fetch:
        src: /var/lib/rancher/k3s/server/tls/server-ca.crt
        dest: "{{ local_secrets_dir }}/{{ cluster_name }}-server-ca.crt"
        flat: true
      delegate_to: localhost
      become: false

    - name: Fetch K3s server key
      fetch:
        src: /var/lib/rancher/k3s/server/tls/server-ca.key
        dest: "{{ local_secrets_dir }}/{{ cluster_name }}-server-ca.key"
        flat: true
      delegate_to: localhost
      become: false

    - name: Fetch K3s client certificate
      fetch:
        src: /var/lib/rancher/k3s/server/tls/client-admin.crt
        dest: "{{ local_secrets_dir }}/{{ cluster_name }}-client-admin.crt"
        flat: true
      delegate_to: localhost
      become: false

    - name: Fetch K3s client key
      fetch:
        src: /var/lib/rancher/k3s/server/tls/client-admin.key
        dest: "{{ local_secrets_dir }}/{{ cluster_name }}-client-admin.key"
        flat: true
      delegate_to: localhost
      become: false

    - name: Fetch K3s node token
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: "{{ local_secrets_dir }}/{{ cluster_name }}-node-token"
        flat: true
      delegate_to: localhost
      become: false

    - name: Set correct permissions on secret files
      file:
        path: "{{ local_secrets_dir }}/{{ cluster_name }}-{{ item }}"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - server-ca.key
        - client-admin.key
        - node-token
      delegate_to: localhost
      become: false

    - name: Set correct permissions on certificate files
      file:
        path: "{{ local_secrets_dir }}/{{ cluster_name }}-{{ item }}"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - server-ca.crt
        - client-admin.crt
      delegate_to: localhost
      become: false

    - name: Display secrets location
      debug:
        msg: |
          Cluster secrets have been copied to: {{ local_secrets_dir }}
          Files copied:
          - {{ cluster_name }}-server-ca.crt
          - {{ cluster_name }}-server-ca.key
          - {{ cluster_name }}-client-admin.crt
          - {{ cluster_name }}-client-admin.key
          - {{ cluster_name }}-node-token
