---
- name: Step 1 — Set hostname and upgrade system
  hosts: pi
  become: true

  tasks:

    - name: Set hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Ensure /etc/hosts entry matches new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+'
        line: "127.0.1.1 {{ new_hostname }}"
        state: present

    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Perform full system upgrade
      apt:
        upgrade: full
        autoremove: yes

    - name: Reboot the system after upgrade
      reboot:
        msg: "Rebooting after full-upgrade"
        pre_reboot_delay: 5
        reboot_timeout: 300
        post_reboot_delay: 15

# --------------------------------------

- name: Step 2 — Disable swap, install iptables, and enable cgroups
  hosts: pi
  become: true

  vars:
    cgroup_options: "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1"
    cmdline_path: "/boot/firmware/cmdline.txt"

  tasks:

    - name: Install iptables
      apt:
        name: iptables
        state: present

    - name: Turn off swap
      command: dphys-swapfile swapoff
      ignore_errors: yes

    - name: Uninstall swap
      command: dphys-swapfile uninstall
      ignore_errors: yes

    - name: Disable swap service
      systemd:
        name: dphys-swapfile
        enabled: false
        state: stopped
      ignore_errors: yes

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^\s*[^#]\S+\s+none\s+swap\s+'
        state: absent
        backup: yes

    - name: Check current cgroup settings
      command: cat "{{ cmdline_path }}"
      register: cmdline_output

    - name: Ensure cgroup options are set in cmdline
      lineinfile:
        path: "{{ cmdline_path }}"
        regexp: '^.*$'
        line: "{{ cmdline_output.stdout | regex_replace('cgroup_enable=.*', '') | trim }} {{ cgroup_options }}"
        backrefs: no
      register: cgroup_line

    - name: Force filesystem sync if cmdline changed
      command: sync
      when: cgroup_line.changed | default(false)

    - name: Wait a bit after sync
      pause:
        seconds: 5
      when: cgroup_line.changed | default(false)

    - name: Mark reboot required if cgroup line changed
      set_fact:
        reboot_required: true
      when: cgroup_line.changed | default(false)

    - name: Mark reboot required if swap was disabled
      set_fact:
        reboot_required: true
      when: ansible_swaptotal_mb > 0

    - name: Reboot if required
      reboot:
        msg: "Rebooting after disabling swap or enabling cgroups"
        pre_reboot_delay: 5
        reboot_timeout: 300
        post_reboot_delay: 15
      when: reboot_required | default(false)