---
- name: Step 3 — Install K3s on master
  hosts: master
  become: true

  tasks:
    - name: Install K3s (master node, without Traefik)
      shell: |
        curl -sfL https://get.k3s.io | sh -s - --disable traefik
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Read node-token from master
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_raw

    - name: Set fact with decoded token
      set_fact:
        k3s_token: "{{ k3s_token_raw.content | b64decode }}"

    - name: Display instructions for copying kubeconfig
      debug:
        msg: |
          K3s master node is ready!
          To copy the kubeconfig to your local machine, run:
          ansible-playbook -i inventory/cluster.ini playbooks/copy-cluster-config.yml

- name: Step 4 — Install K3s on workers
  hosts: workers
  become: true

  vars:
    master_node: "{{ groups['master'][0] }}"
    k3s_url: "https://{{ hostvars[master_node]['ansible_host'] }}:6443"
    k3s_token: "{{ hostvars[master_node]['k3s_token'] | trim }}"

  tasks:
    - name: Install K3s (worker node)
      shell: |
        curl -sfL https://get.k3s.io | sh -
      environment:
        K3S_URL: "{{ k3s_url }}"
        K3S_TOKEN: "{{ k3s_token }}"
      args:
        creates: /etc/rancher/k3s/k3s.yaml