image:
  repository: intothefathom/starknet-indexer.stablecoin.indexer
  tag: dev-e56bc6b

env:
  postgres:
    host: postgres-service
    port: 5432
    db: indexer

  rpc:
    endpoint: "https://lb.drpc.org/ogrpc?network=starknet&dkey=xxx"
    ws_endpoint: "wss://lb.drpc.org/ogws?network=starknet&dkey=xxx"

  start_block: "1417000"
  resume_from_last_signature: false

  log:
    level: debug
    save: true

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi