apiVersion: v1
kind: Namespace
metadata:
  name: krakend-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-service-account
  namespace: krakend-lab
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krakend-service-account
  namespace: krakend-lab
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
  namespace: krakend-lab
spec:
  replicas: 1
  selector:
    matchLabels: { app: echo-api }
  template:
    metadata:
      labels: { app: echo-api }
    spec:
      serviceAccountName: echo-service-account
      containers:
        - name: echo
          # Simple HTTP echo server that returns method, path, headers, body as JSON
          image: ealen/echo-server:0.9.0
          ports:
            - containerPort: 80
          # Optional: set a banner to easily recognize responses
          env:
            - name: ENABLE__ENV
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-api
  namespace: krakend-lab
spec:
  selector: { app: echo-api }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: krakend-lab
data:
  krakend.json: |
    {
      "version": 3,
      "name": "krakend-smoke-v2",
      "port": 8080,
      "timeout": "5s",
      "extra_config": {
        "telemetry/opencensus": {
          "reporting_period": 1,
          "exporters": {
            "prometheus": {
              "port": 8090,
              "namespace": "krakend"
            }
          }
        }
      },
      "endpoints": [
        {
          "endpoint": "/probe/echo",
          "method": "GET",
          "output_encoding": "json",
          "headers_to_pass": ["Authorization","X-Request-Id","X-API-Key"],
          "input_query_strings": ["q","page","page_size","limit","offset","foo","bar","lang","locale","sort"],
          "backend": [
            {
              "host": ["http://echo-api.krakend-lab.svc.cluster.local"],
              "url_pattern": "/",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/probe/echo",
          "method": "POST",
          "output_encoding": "json",
          "headers_to_pass": ["Authorization","X-Request-Id","Content-Type"],
          "backend": [
            {
              "host": ["http://echo-api.krakend-lab.svc.cluster.local"],
              "url_pattern": "/",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/probe/echo/headers",
          "method": "GET",
          "output_encoding": "json",
          "backend": [
            {
              "host": ["http://echo-api.krakend-lab.svc.cluster.local"],
              "url_pattern": "/",
              "encoding": "json",
              "extra_headers": {
                "X-From-Krakend": "1"
              }
            }
          ]
        },
        {
          "endpoint": "/api/v1/public",
          "method": "GET",
          "output_encoding": "json",
          "backend": [
            {
              "host": ["http://echo-api.krakend-lab.svc.cluster.local"],
              "url_pattern": "/",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/api/v1/protected",
          "method": "GET",
          "output_encoding": "json",
          "extra_config": {
            "auth/validator": {
              "cache": true,
              "cache_duration": 86400,
              "alg": "RS256",
              "jwk_url": "http://keycloak.keycloak.svc.cluster.local:8080/realms/rakia/protocol/openid-connect/certs",
              "disable_jwk_security": true,
              "audience": ["krakend-test"],
              "issuer": "http://keycloak.keycloak.svc.cluster.local:8080/realms/rakia",
              "propagate_claims": [
                ["sub", "x-id"],
                ["preferred_username", "x-user"],
                ["realm_access.roles", "x-roles"]
              ]
            }
          },
          "input_headers": [
            "Authorization",
            "x-id",
            "x-user",
            "x-roles"
          ],
          "backend": [
            {
              "host": ["http://echo-api.krakend-lab.svc.cluster.local"],
              "url_pattern": "/",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/api/v1/admin",
          "method": "GET",
          "output_encoding": "json",
          "extra_config": {
            "auth/validator": {
              "cache": true,
              "cache_duration": 86400,
              "alg": "RS256",
              "jwk_url": "http://keycloak.keycloak.svc.cluster.local:8080/realms/rakia/protocol/openid-connect/certs",
              "disable_jwk_security": true,
              "audience": ["krakend-test"],
              "issuer": "http://keycloak.keycloak.svc.cluster.local:8080/realms/rakia",
              "propagate_claims": [
                ["sub", "x-id"],
                ["preferred_username", "x-user"],
                ["realm_access.roles", "x-roles"]
              ]
            }
          },
          "input_headers": [
            "Authorization",
            "x-id",
            "x-user",
            "x-roles"
          ],
          "backend": [
            {
              "host": ["http://echo-api.krakend-lab.svc.cluster.local"],
              "url_pattern": "/",
              "encoding": "json"
            }
          ]
        },
        {
          "endpoint": "/v1/person/",
          "method": "GET",
          "output_encoding": "json",
          "backend": [
            {
              "sd": "static",
              "host": [
                "echo-api.krakend-lab.svc.cluster.local:80"
              ],
              "url_pattern": "/person/",
              "encoding": "json",
              "method": "GET"
            }
          ],
          "extra_config": {
            "auth/validator": {
              "cache": true,
              "cache_duration": 86400,
              "alg": "RS256",
              "jwk_url": "http://keycloak.keycloak.svc.cluster.local:8080/realms/rakia/protocol/openid-connect/certs",
              "disable_jwk_security": true,
              "propagate_claims": [
                ["sub", "x-id"],
                ["preferred_username", "x-user"],
                ["realm_access.roles", "x-roles"]
              ]
            }
          },
          "input_headers": [
            "Authorization",
            "x-id",
            "x-user",
            "x-roles"
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-bff
  namespace: krakend-lab
spec:
  replicas: 1
  selector:
    matchLabels: { app: krakend-bff }
  template:
    metadata:
      labels: { app: krakend-bff }
    spec:
      serviceAccountName: krakend-service-account
      containers:
        - name: krakend
          image: krakend:2.11.0
          args: ["run", "-c", "/etc/krakend/krakend.json"]
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8090
          readinessProbe:
            httpGet:
              path: /__health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /__health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: 
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits: 
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: cfg
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
      volumes:
        - name: cfg
          configMap:
            name: krakend-config
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-bff
  namespace: krakend-lab
spec:
  selector: { app: krakend-bff }
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 8090
      targetPort: 8090
  type: ClusterIP
