# Stable service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stable
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---

# Canary service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080