---
galaxy_info:
  author: k3s-cluster
  description: Copy K3s cluster configuration to local machine
  company: k3s-cluster
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 24.04
  galaxy_tags:
    - kubernetes
    - k3s
    - config

dependencies: []
